#!/usr/bin/env sh
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
#YABAI STUFF

# My custom space names for my 3 monitor setup. These names are used in some of my scripts.
yabai -m space 1 --label Code
yabai -m space 2 --label Browser
yabai -m space 3 --label Message

# bsp or float (default: bsp)
yabai -m config layout bsp

yabai -m config top_padding    15
yabai -m config bottom_padding 15
yabai -m config left_padding   15
yabai -m config right_padding  15
yabai -m config window_gap     15

yabai -m config active_window_border_topmost off
yabai -m config focus_follows_mouse         off
yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float
yabai -m config mouse_follows_focus          off
yabai -m config window_placement second_child

yabai -m config window_opacity_duration 0.00
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0
yabai -m config window_border on
yabai -m config window_border_width 3
yabai -m config active_window_border_color 0xff775759
yabai -m config insert_feedback_color 0xFFA3BE8C

#yabai -m config --space 4 layout float
#yabai -m config --space 5 layout float

# add 20 padding to the top and 0 padding to the bottom of every space located on the main display
yabai -m config external_bar main:25:0
# add 20 padding to the top and bottom of all spaces regardless of the display it belongs to
yabai -m config external_bar all:30:0

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^Chrome" space=^Browser
yabai -m rule --add app="^Min$" space=^Browser

yabai -m rule --add app="^Finder$" space=^Float

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on manage=off
yabai -m rule --add app="^Message" manage=off

yabai -m rule --add app="^Skype" space=^Message
yabai -m rule --add app="^Messenger" space=^Message
yabai -m rule --add app="^Zalo" space=^Message 

echo "Yabai configuration loaded... 0_0"
